# Generated by Django 6.0.1 on 2026-02-11 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Уникальный код предмета, например: math_profile, russian, physics', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Название предмета, например: Русский', max_length=255)),
                ('max_score', models.PositiveIntegerField(help_text='Максимальное количество первичных баллов по предмету')),
                ('tasks_count', models.PositiveIntegerField(help_text='Количество заданий в экзамене')),
                ('year', models.PositiveSmallIntegerField(help_text='Год экзамена')),
            ],
            options={
                'verbose_name': 'Экзаменационный предмет',
                'verbose_name_plural': 'Экзаменационные предметы',
            },
        ),
        migrations.CreateModel(
            name='ExamTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='Номер задания в экзамене')),
                ('title', models.CharField(help_text='Название задания, например: Планиметрия', max_length=255)),
                ('max_score', models.PositiveIntegerField(help_text='Максимальное количество баллов за задание')),
                ('exam_subject', models.ForeignKey(help_text='Предмет, к которому относится задание', on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='static_exam_info.examsubject')),
            ],
            options={
                'verbose_name': 'Шаблон задания',
                'verbose_name_plural': 'Шаблоны заданий',
                'ordering': ['exam_subject', 'number'],
            },
        ),
    ]
