# Generated by Django 6.0.1 on 2026-03-02 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_exam_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScoreConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_score', models.PositiveIntegerField()),
                ('secondary_score', models.PositiveIntegerField()),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_conversions', to='static_exam_info.examsubject')),
            ],
        ),
    ]
