# Generated by Django 6.0.1 on 2026-02-19 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Название пробника (например, Пробник №1)', max_length=255)),
                ('date_taken', models.DateField(auto_now_add=True, help_text='Дата прохождения пробника')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Пробник',
                'verbose_name_plural': 'Пробники',
            },
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='Номер задачи в пробнике')),
                ('result', models.CharField(choices=[('correct', 'Верно'), ('wrong', 'Неверно')], default='wrong', help_text='Результат решения задачи')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tests.test')),
            ],
            options={
                'verbose_name': 'Задача пробника',
                'verbose_name_plural': 'Задачи пробников',
            },
        ),
    ]
