# Generated by Django 6.0.1 on 2026-04-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активен ли предмет (выбран пользователем сейчас)'),
        ),
    ]
