# Generated by Django 6.0.1 on 2026-02-26 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_exam_info', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='number',
        ),
        migrations.AddField(
            model_name='task',
            name='exam_task_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='static_exam_info.examtasktemplate'),
        ),
    ]
